### ISSUE TITLE
Fix embedded-mongo stacktrace

### ISSUE THREAD

**Issue by seppaleinen** [seppaleinen/krog-rouletten#5]
Embedded-mongo plugin throws stacktraces when shutting down..

Exception in thread "Thread-4" java.lang.NoClassDefFoundError: de/flapdoodle/embed/process/extract/ExtractedFileSets
	at de.flapdoodle.embed.process.store.ArtifactStore.removeFileSet(ArtifactStore.java:90)
	at de.flapdoodle.embed.process.store.CachingArtifactStore$FilesWithCounter.forceDelete(CachingArtifactStore.java:176)
	at de.flapdoodle.embed.process.store.CachingArtifactStore.removeAll(CachingArtifactStore.java:100)
	at de.flapdoodle.embed.process.store.CachingArtifactStore$CacheCleaner.run(CachingArtifactStore.java:196)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: de.flapdoodle.embed.process.extract.ExtractedFileSets
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more

**Comment by seppaleinen** [comment]
Fixed by downgrading embedmongo-maven-plugin from 0.3.4 to 0.3.3
